title: "Fermin Lassa"
username: "lassa97"
profile_picture: "https://avatars.githubusercontent.com/u/40122711?s=460&u=c5b9c22c402980a5c6a3d06122bc4dcc01a2766f&v=4"

email: "fermin@lassa.net"
description: >-
  Personal portfolio and blog. Posts about programming and
  cybersecurity.
baseurl: ""
url: "https://fermin.lassa.net"
github_username: "lassa97"
rss: "RSS Feed"

# Post settings
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - about
  - lassa97
  - media
  - projects.md
